### ISSUE TITLE
minifab gets stuck bringing up the network

### ISSUE THREAD

**Issue by mvkillu** [hyperledger-labs/minifabric#129]
Pls help me debug the issue. I have a spec file that was working fine on Ubuntu 20.04 a couple of weeks back, but not working anymore. It's working fine on Windows 10. 

OS: OS: Ubuntu 20.04.1 LTS x86_64
Docker version 19.03.13, build 4484c46d9d

### spec.yaml
```
fabric:
  cas:
  - "ca1.dfp.com"
  - "ca1.amc.com"
  peers:
  - "peer1.dfp.com"
  - "peer1.amc.com"
  orderers:
  - "orderer1.dff.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
```

The command I ran was: **minifab netup -o dfp.com -e true -f default**

The last few lines of the output is: 
```
TASK [Start all ca nodes] ******************************************************
changed: [minifab] => (item={'fullname': 'ca1.dfp.com', 'mspid': 'dfp-com', 'name': 'ca1', 'org': 'dfp.com', 'port': '7054', 'portmap': '', 'type': 'ca', 'url': 'ca1.dfp.com'})
changed: [minifab] => (item={'fullname': 'ca1.amc1.com', 'mspid': 'amc1-com', 'name': 'ca1', 'org': 'amc1.com', 'port': '7054', 'portmap': '', 'type': 'ca', 'url': 'ca1.amc1.com'})

TASK [Error!] ******************************************************************
skipping: [minifab]

TASK [Set tool gopath] *********************************************************
ok: [minifab]

TASK [Start cli container for all fabric operations] ***************************
changed: [minifab]

TASK [wait for 3 seconds and orderer nodes to select leader] *******************
ok: [minifab]

TASK [generate the script to check status] *************************************
changed: [minifab]

TASK [Run the orderer raft leader election script on cli container] ************
```

And it gets stuck there for a long time. Could you help me debug the issue? The code was working fine on Windows 10, so I suspect its not issue with spec.yaml

**Comment by litong01** [comment]
Can you do minifab cleanup, then do the command again?

**Comment by litong01** [comment]
I wonder if you are using very old minifab script , please check if your script still uses hfrd/minifab:latest image.

**Comment by mvkillu** [comment]
My minifab is latest. In fact I setup the environment on a clean ubuntu installation. I also tried minifab cleanup. 

```
#!/bin/bash
[ ! -d "$(pwd)/vars" ] && mkdir vars
ADDRS=$(ifconfig|grep 'inet '|grep -v '\.1 '|tr -s ' '|awk '{$1=$1};1'|cut -d ' ' -f 2|cut -d '/' -f 1|paste -sd "," -|sed s/addr://g)
if [ -f "$(pwd)/spec.yaml" ]; then
  echo "Using spec file: $(pwd)/spec.yaml"
  docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
  -v $(pwd)/spec.yaml:/home/spec.yaml -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
else
  echo "Using default spec file"
  docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
  -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
fi
```

**Comment by mvkillu** [comment]
I tried it again this morning, and it worked fine. I swear I didn't make any changes and it was working with the same code. Not sure what went wrong the last few times I tried. Closing the issue. Thank you.

```
alvin@calvin-2004:~/code/mfbc$ minifab netup -o dfp.com -e true
Using spec file: /home/calvin/code/mfbc/spec.yaml
Minifab Execution Context:
    FABRIC_RELEASE=2.3.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=true
    CURRENT_ORG=dfp.com
    HOST_ADDRESSES=192.168.0.103
    WORKING_DIRECTORY: /home/calvin/code/mfbc
....
# Preparing for the following operations: *********************
  verify options, download images, generate certificates, start network, network status
.................
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  download images
............
# Running operation: ******************************************
  generate certificates
........................................................................................................
# Running operation: ******************************************
  start network
.......................
# Running operation: ******************************************
  network status
.......
# Docker node status ******************************************
  5838b44a80_cli : Up 7 seconds
  ca1.amc.com : Up 8 seconds
  ca1.dfp.com : Up 9 seconds
  orderer1.dff.com : Up 10 seconds
  peer1.amc.com : Up 11 seconds
  peer1.dfp.com : Up 12 seconds

# Fabric network peer and orderer node health status **********
         peer1.dfp.com "OK"
         peer1.amc.com "OK"
      orderer1.dff.com "OK"
  Network Status: 100%


# STATS *******************************************************
minifab: ok=189	failed=0	

real	1m34.126s
user	1m24.598s
sys	0m12.326s
```

**Comment by mvkillu** [comment]
It seems the process is stuck when there are two entries in the orderers section of the spec file. Is it something I am doing wrong, or something wrong with my system? I tested with just one orderer (orderer1.dff.com) and it worked fine. But when I add 'orderer1.amc1.com' I am getting the issue.

```
fabric:
  cas:
    - 'ca1.dfp.com'
    - 'ca1.amc1.com'
  peers:
    - 'peer1.dfp.com'
    - 'peer1.amc1.com'
  orderers:
    - 'orderer1.dff.com'
    - 'orderer1.amc1.com'
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
```
