### ISSUE TITLE
Not able to start a smaller network than default

### ISSUE THREAD

**Issue by rranjan3** [hyperledger-labs/minifabric#132]
Try to startup a minimal Fabric network instead of the default one. For this, use the modified spec.yaml file to look like -
```
fabric:
  cas:
  - "ca1.org0.example.com"
  peers:
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
```
The Fabric network fails to spawn. Is there something else that needs to be done as well?

**Comment by litong01** [comment]
Orderer and peer orgs must be different. There is no penalties to have two different orgs for a network. Try to make either your peer or orderer org different, you should be fine. Please close this one since this is not a supported use case.

**Comment by rranjan3** [comment]
The below network does spin up -
```
fabric:
  cas:
  - "ca1.org0.example.com"
  peers:
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  orderers:
  - "orderer1.org1.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
```
Thanks @litong01 for the direction. Closing as the issue stated above is not valid.
