### ISSUE TITLE
request: minifab netup on given docker network

### ISSUE THREAD

**Issue by itaru2622** [hyperledger-labs/minifabric#143]
Currently, minifab netup command creates new docker network(hash based name), and runs fabric containers on it.
It is good if minifabric can netup on given docker network.

If the above is achieved, adding fabric capability for existing service is easy, as bellow:
```shell
docker network create specific_network
docker run -d --network specific_network someservice
minifabric netup     # fabric containers runs on specific_network 
docker run -d --network specific_network otherservice
```
It can be done by specifing NETNAME  from spec.yaml or command line option. 
 
bellow is spec.yaml version:
```yaml
# spec.yaml
fabric:
  network: "specific_network" #  use as {{NETNAME}}
  cas:
  - "ca1.org0.example.com"
  peers:
  - "peer1.org0.example.com"
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"
```

```patch
diff --git a/fabops.yaml b/fabops.yaml
index be00c3f..7b990bb 100644
--- a/fabops.yaml
+++ b/fabops.yaml
@@ -16,7 +16,13 @@

     - set_fact:
         CLINAME: "{{ current_location_hash[:10] }}_cli"
+
+    - set_fact:
         NETNAME: "{{ current_location_hash[:10] }}_net"
+      when: fabric.network is undefined
+    - set_fact:
+        NETNAME: "{{ fabric.network }}"
+      when: fabric.network is defined
```

**Comment by litong01** [comment]
@itaru2622 as you have already found, you can use the generated network name which is always static as long as your working directory remains same to do what you asked. You can also submit a PR to support it. Please include few lines in one of the docs in the docs directory to describe this new parameter, the parameter should be in the settings section like this.

```
fabric:
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
    netname: whatever
```

**Comment by litong01** [comment]
@itaru2622 please also make sure that the CLINAME to be made consistent with the network name which was the case before this feature.

**Comment by itaru2622** [comment]
@litong01 thank you for your response. 

before submitting PR,  where should I put 'network name' in spec.yaml ?
the above sample is fabric.network but you may prefer others place, such as fabric.settings.network etc. 
as you mentioned above, it may be good to consider for configurable CLINAME...
anyway, which yaml path is good for you ? any idea or suggestion? 
I think choice C is better than other.
```yaml
# choice A
 fabric:
     network:
     cliname:

# choice B
 fabric:
    settings:
       network:
       cliname:

# choice C
 fabric:
    settings:
       docker:
          network:
          cliname:
```

**Comment by litong01** [comment]
@itaru2622 I would prefer choice #A or #B, and think that simply set the cliname to be the same as netname (not network), so that we have one fewer configuration to consider. I've been trying really hard to not pile up big spec.yaml file. The goal is to make the spec.yaml file as simple as possible but still give a lot of flexibility (configurability). Please see the current spec.yaml file for other similar configuration parameters. And in your PR, please also change the spec.yaml but all commented as existing ones. Thanks for your contribution.

```
 ### use go proxy when default go proxy is restricted in some of the regions.
  ### the default goproxy
  # goproxy: "https://proxy.golang.org,direct"
  ### the goproxy in China area
  # goproxy: "https://goproxy.cn,direct"
  ### set the endpoint address to override the automatically detected IP address
  # endpoint_address: 1.2.3.4
```

**Comment by itaru2622** [comment]
@litong01 ok, I will take choice #A.
I'd like to confirm some about cliname in your last comment.

Did you mean I should take bellow choice #D but not  #E ?
```yaml
# choice D ( both netname and cliname will be changed if netname is specified in spec.yaml) 
    - set_fact:
        CLINAME: "{{ current_location_hash[:10] }}_cli"
        NETNAME: "{{ current_location_hash[:10] }}_net"
      when: fabric.netname is undefined

    - set_fact:
        CLINAME: "{{ fabric.netname }}_cli"
        NETNAME: "{{ fabric.netname }}"
      when: fabric.netname is defined

# choice E (netname and cliname are configurable separately)
   - set_fact:
        CLINAME: "{{ current_location_hash[:10] }}_cli"
      when: fabric.cliname is undefined
   - set_fact:
        CLINAME: "{{ fabric.cliname }}"
      when: fabric.cliname is defined

    - set_fact:
        NETNAME: "{{ current_location_hash[:10] }}_net"
      when: fabric.netname is undefined
    - set_fact:
        NETNAME: "{{ fabric.netname }}"
      when: fabric.netname is defined
```
