### ISSUE TITLE
Feature suggestion: adjust BatchTimeout and BatchSize

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger-labs/minifabric#151]
Currently, batch time out and batch size are hard coded in playbooks/ops/certgen/templates/configtx.j2
```
  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
```

as I have a project investigating relationship between performance and those parameters above.
https://github.com/SamYuan1990/Probe
https://github.com/SamYuan1990/Probe/blob/main/doc/HowToConfigFabricParameters.md

I would like request a feature(s) that allow minifab user to adjust those parameters via
Some specific config/items in spec.yaml. (such as #147)
Some functions supported as `channelsign,channelupdate` (I am not sure if update in AddNewOrganization.md, can make this happen or not?)

**Comment by litong01** [comment]
@SamYuan1990 I think we've talked about this before. Currently you can simply add following parameters in your spec.yaml file to make them the way you wanted.

```
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
      GENERAL_ORDERER_BATCHTIMEOUT: 5s
      GENERAL_ORDERER_MATCHSIZE_MAXMESSAGECOUNT: 500
      GENERAL_ORDERER_BATCHSIZE_ABSOLUTEMAXBYTES: 120MB
      GENERAL_ORDERER_BATCHSIZE_PREFERREDMAXBYTES: 2048 KB
```
I think these parameters will work. After network is up running, you can use channel update command to make changes to these parameters. Not exactly sure why there is a need for a new way to do this parameters.
