### ISSUE TITLE
Unable to change  BATCHTIMEOUT and BATCHSIZE

### ISSUE THREAD

**Issue by urkaitz** [hyperledger-labs/minifabric#196]
Following issue #151 here is my spec.yaml

```
  settings:
    ca:
      FABRIC_LOGGING_SPEC: INFO
    peer:
      FABRIC_LOGGING_SPEC: INFO
      CORE_CHAINCODE_LOGGING_LEVEL: INFO
    orderer:
      FABRIC_LOGGING_SPEC: INFO
      GENERAL_ORDERER_BATCHTIMEOUT: 10s
      GENERAL_ORDERER_BATCHSIZE_MAXMESSAGECOUNT: 500
      GENERAL_ORDERER_BATCHSIZE_ABSOLUTEMAXBYTES: 120MB
      GENERAL_ORDERER_BATCHSIZE_PREFERREDMAXBYTES: 2048 KB
```

Then generate the network with:
minifab up

Then launch a script that generates a lot of tx.

The block size is 10 and the time is around 2sg, it seems that something I'm doing wrong. Are correct the env variables? Are inside the rigth place?
