### ISSUE TITLE
Error during adding a new organization

### ISSUE THREAD

**Issue by ivanv6** [hyperledger-labs/minifabric#199]
Dear all, i'm following the docs to add a new organization. I encountered this error:

```
$ sudo ./minifab approve,discover,commit
Using spec file: /home/security/s4r-blockchain/spec.yaml
Minifab Execution Context:
    FABRIC_RELEASE=2.3.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=couchdb
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="invoke","a","b","5"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=7000
    CURRENT_ORG=org0.ac.com
    HOST_ADDRESSES=10.0.4.110
    WORKING_DIRECTORY: /home/security/s4r-blockchain
.......
# Preparing for the following operations: *********************
  verify options, cc approve, discover, cc commit
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  cc approve
......
# Running operation: ******************************************
  discover
........................
# Discover endorsers results **********************************
  Chaincode endorsers file: ./vars/discover/mychannel/simple_endorsers.json
# Discover orderers results ***********************************
  Channel orderers file: ./vars/discover/mychannel/ordererendpoints.json
# Running operation: ******************************************
  cc commit
..........
# Select a random endorser group ******************************
  The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'Layouts'
  
  The error appears to be in '/home/playbooks/common/peerselection.yaml': line 25, column 5, but may
  be elsewhere in the file depending on the exact syntax problem.
  
  The offending line appears to be:
  
  
    - name: Select a random endorser group
      ^ here
  

# STATS *******************************************************
minifab: ok=67	failed=1	

real	0m16.213s
user	0m9.832s
sys	0m2.399s
```

Could you please help me? Thanks

**Comment by litong01** [comment]
@ivanv6 when you do netup or creating new channel, you probably did not do anchorupdate which setup anchor node for discovery to work. If you do anchorupdate, you should be ok. Give it a try and if that is the issue, please close this, otherwise, please detail entire steps so that others can possibly recreate the issue and see what might have gone wrong.

**Comment by litong01** [comment]
Any updates on this? If not, please close this.

**Comment by alphacybercom** [comment]
Hi, by following the [Expand an existing network with a new org tutorial](https://github.com/hyperledger-labs/minifabric/blob/main/docs/ExpandYourNetwork.md), I've tried with a brand new installation with two nodes (in two separate VMs).

Used `specs.yaml` files.
**org0:**
```
fabric:
  cas:
  - "ca1.org0.company.com"
#  - "ca1.org1.example.com"
  peers:
  - "peer1.org0.company.com"
#  - "peer2.org0.example.com"
#  - "peer1.org1.example.com"
#  - "peer2.org1.example.com"
  orderers:
  - "orderer1.company.com"
  - "orderer2.company.com"
  - "orderer3.company.com"
  - "orderer4.company.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
  ### use go proxy when default go proxy is restricted in some of the regions.
  ### the default goproxy
  # goproxy: "https://proxy.golang.org,direct"
  ### the goproxy in China area
  # goproxy: "https://goproxy.cn,direct"
  ### set the endpoint address to override the automatically detected IP address
  # endpoint_address: 
  ### set the docker network name to override the automatically generated name.
  netname: "mynet"
  ### set the extra optins for docker run command
  # container_options: "--restart=always --log-opt max-size=10m --log-opt max-file=3"
```

**org1:**
```
fabric:
  cas:
#  - "ca1.org0.company.com"
  - "ca1.org1.company.com"
  peers:
#  - "peer1.org0.company.com"
#  - "peer2.org0.example.com"
  - "peer1.org1.company.com"
#  - "peer2.org1.example.com"
#  orderers:
#  - "orderer1.company.com"
#  - "orderer2.company.com"
#  - "orderer3.company.com"
#  - "orderer4.company.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
  ### use go proxy when default go proxy is restricted in some of the regions.
  ### the default goproxy
  # goproxy: "https://proxy.golang.org,direct"
  ### the goproxy in China area
  # goproxy: "https://goproxy.cn,direct"
  ### set the endpoint address to override the automatically detected IP address
  # endpoint_address: 
  ### set the docker network name to override the automatically generated name.
  netname: "mynet"
  ### set the extra optins for docker run command
  # container_options: "--restart=always --log-opt max-size=10m --log-opt max-file=3"
```

Here you can find the updated order of commands executed (with initial node).

```
user@org0: sudo ./minifab up -e 7000 -s couchdb -o org0.company.com
user@org1: sudo ./minifab netup -e 5000 -s couchdb -o org1.company.com
user@org1: scp vars/JoinRequest_org1-company-com.json user@org0:~/minifab/vars/NewOrgJoinRequest.json
user@org0: sudo ./minifab orgjoin
user@org0: scp ~/minifab/vars/profiles/endpoints.yaml user@org1:~/minifab/vars/
user@org1: sudo ./minifab nodeimport,join
user@org0: sudo ./minifab approve,discover,commit
```

At this point, I get the attached error.
<img width="1041" alt="Screenshot" src="https://user-images.githubusercontent.com/61021242/120623807-59f40180-c460-11eb-9eb9-0d9b1fc32b87.png">
