### ISSUE TITLE
minifab for k8s does not meet client.authentication.k8s.io ( k8s credential and authentication extension )

### ISSUE THREAD

**Issue by itaru2622** [hyperledger-labs/minifabric#212]
some cloud k8s, like AWS ESK, requires credential and authentication extension to operate k8s as described below URLs.
- https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html  describes EKS requires client.authentication.k8s.io
- https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html  describes setting up  AWS credential into ${HOME}/.aws

current minifab container doesn't have feature to load and involve these extension, so minifab failed to setup HLF on AWS EKS.

but with small modification as followings, minifab can setup HLF on AWS EKS.

```bash
# extra options to set minifab container
export MINIFAB_OPTS='-v /home/my/.aws:/root/.aws -v /somewhere/aws-iam-authenticator:/usr/local/bin/aws-iam-authenticator'
# start minifab
minifab netup ...
```
```patch
diff --git a/minifab b/minifab
--- a/minifab
+++ b/minifab
   docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
-  -v $(pwd)/spec.yaml:/home/spec.yaml -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
+  -v $(pwd)/spec.yaml:/home/spec.yaml -e "ADDRS=$ADDRS" ${MINIFAB_OPTS} hyperledgerlabs/minifab:latest /home/main.sh "$@"
```

**Comment by itaru2622** [comment]
@litong01 I'm not sure what name is better for above environment variable, MINIFAB_OPT is ok? or any suggestion?

**Comment by litong01** [comment]
You can actually create a correct kubeconfig file which contains access token, then everything will work fine. I've tested against eks which worked fine.

Use aws eks get-token to get access token then use kibectl config set-credentials to get the access token inside the kube config file. Use that kube config like any other ones. Things will work great. 

Please close this issue.

**Comment by itaru2622** [comment]
@litong01 I tested the way you suggested with 'eksctl create cluster' command. and found your suggestion requires manual editing kubeconfig.

just after 'eksctl create cluster' command execution, kubeconfig file assumes to use aws or aws-iam-authenticator as described in the above URL.

after get-token and set-credentials, kubeconfig snippet became as bellow.
at this moment, kubectl failed because of   'aws command not found'. 
To succeeded it, I need to delete 'execute' section from kubeconfig by manual.

on the other hand, my above method needs no modification.

I found both methods can operate AWS EKS, but my method is more easier than yours.
I'd like to confirm you have no plan to merge  my above method?

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...    
users:
- name: arn:aws:eks:REGION:ID:cluster/CLUSTERNAME
    exec: # still remains this section and need to delete  for using embeded token.
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args: ...
    token: value which got by aws eks get-token
```
