### ISSUE TITLE
It needs the way to pass fabric server command args for reducing potential risks in deployed fabric network.

### ISSUE THREAD

**Issue by itaru2622** [hyperledger-labs/minifabric#243]
current minifabric supports to change server behavior by specifying environment variables in spec.yaml  but no way to pass command args to fabric servers

for example, fabric-ca server has lots of command args, described as bellow:
https://github.com/hyperledger/fabric-ca/blob/release-1.4/docs/source/servercli.rst
it supports to specify (A) admin password and (B) policies related to identities/affiliations.

but minifabric has no way to pass those command args.
as the result, we has to use default admin password and policies for identities/affiliations.
then, there are potential risks in deployed fabric network.

**Comment by itaru2622** [comment]
the basic idea is specifying command args via spec.yaml as bellow:
```yaml
# spec.yaml
fabric:
  cas:
  peers:
  orderers:
  settings:
       :
  command_args:
     ca:  "--boot adminuser:adminpassword --cfg.identities.allowremove"
     peer: ...
     orderer: ...
```
the above may hard to pick up admin id/password from given strings, to fill connection profile...

the improving idea is hybrid of reserved variables in settings and command_args via spec.yaml
```yaml
# spec.yaml
fabric:
  : 
  settings:
      ca:
        adminID: "adminuser"
        adminPass: "adminpassword"
       :
  command_args:
     ca:  "--boot ${adminID}:${adminPass} --cfg.identities.allowremove"
     peer: ...
     orderer: ...
```
