### ISSUE TITLE
Add New Organization

### ISSUE THREAD

**Issue by webzest** [hyperledger-labs/minifabric#311]
Hi,

I created my spec.yaml file and added an extra org, peer and orderer:
```
fabric:
  cas:
  - "ca1.org0.example.com"
  - "ca1.org1.example.com"
  - "ca1.org2.example.com"
  - "ca1.org3.example.com"
  peers: 
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  - "peer1.org1.example.com"
  - "peer2.org1.example.com"
  - "peer1.org2.example.com"
  - "peer2.org2.example.com"  
  - "peer1.org3.example.com"
  - "peer2.org3.example.com"  
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"
  - "orderer4.example.com"  
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
  ### use go proxy when default go proxy is restricted in some of the regions.
  ### the default goproxy
  # goproxy: "https://proxy.golang.org,direct"
  ### the goproxy in China area
  # goproxy: "https://goproxy.cn,direct"
  ### set the endpoint address to override the automatically detected IP address
  ### could be a public IP address or a dns name
  # endpoint_address: 104.196.45.144
  ### set the docker network name to override the automatically generated name.
  netname: "mysite"
  ### set the extra options for docker run command
  # container_options: "--restart=always --log-opt max-size=10m --log-opt max-file=3"
```

Now, I would like to add a new Organization.  I read the Doc from: https://github.com/hyperledger-labs/minifabric/blob/main/docs/AddNewOrganization.md
It is assuming that I already have either a JoinRequest json or al already generated json with the new Org data.  Suppose I do not have either of those and would like to add a new Organization, after my first launch, how do I generate the JoinRequest file with the new Org info?
