### ISSUE TITLE
 Default option org is org0 which does not exist in your spec

### ISSUE THREAD

**Issue by webzest** [hyperledger-labs/minifabric#313]
Hi,

on my First Run of minifabric, I created a spec file with the following:

```
fabric:
  cas:
  - "ca1.org0.domain.com"
  - "ca1.org1.domain.com"
  peers: 
  - "peer1.org0.domain.com"
  - "peer2.org0.domain.com"
  orderers:
  - "orderer1.domain.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG

  netname: "ClearArmor"

```
Then, I launched the minifab in this manner:

```
./minifab up -i 2.4.1 -o org0.domain.com
```

It launched without issues.  then I tried it again, by performing a cleanup:
```
./minifab cleanup

```
I got this error:

```
# Verify the organization option ******************************
  Default option org is org0.domain.com which does not exist in your spec, use -o to specify one
```

I tried again with this approach:
```
./minifab cleanup -o org0.domain.com
```

I received the same this error:

```
# Verify the organization option ******************************
  Default option org is org0.domain.com which does not exist in your spec, use -o to specify one
```
