### ISSUE TITLE
No such container: mysite 

### ISSUE THREAD

**Issue by intchensc** [hyperledger-labs/minifabric#332]
I had changed my `spec.yaml`, just set the netname to "chainoa"
```
fabric:
  cas:
  - "ca.org0.example.com"
  - "ca.org1.example.com"
  peers: 
  - "peer1.org0.example.com"
  - "peer1.org1.example.com"
  orderers:
  - "orderer1.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
  goproxy: "https://goproxy.cn,direct"
  netname: "chainoa"
``` 

when I want to use`minifab ccup -n record -l go -v 1.0` to install my chaincode `record`
It prints blow:
```
# Preparing for the following operations: *********************
  verify options, cc install, cc approve, cc commit, cc initialize, discover, channel query
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  cc install
.......
# Run the chaincode install script on cli container ***********
  non-zero return code
  Error: No such container: mysite

# STATS *******************************************************
minifab: ok=34  failed=1

real    0m6.295s
user    0m5.768s
sys     0m0.899s

```
